server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '12345!Fra'
  jpa:
    properties:
      hibernate:
      temp:
        use_jdbc_metadata_defaults: false

security:
  keyStore:
    location: classpath:keystore.jks
    alias: mytest
    keypass: mypass
    storepass: mypass
  authserver-scopename-all-access: auth_all
  encoding-strength: 10
  security-realm: Spring Boot JWT Example Realm

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG